---
apiVersion: v1
kind: Endpoints
metadata: 
  name: minio
  namespace: network
  labels: 
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
subsets: 
  - addresses: 
      - ip: ${SYNOLOGY_ADDR}
    ports: 
      - name: http
        port: 9090
      - name: minio
        port: 9000
---
apiVersion: v1
kind: Service
metadata: 
  name: minio
  namespace: network
  labels: 
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
spec:
  ports: 
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: minio
      port: 9000
      protocol: TCP
      targetPort: 9000
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: network
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels: 
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
spec:
  ingressClassName: nginx-internal
  rules:
  - host: minio.${INTERNAL_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9090
  tls: 
    - hosts:
        - minio.${INTERNAL_DOMAIN}
      secretName: minio-tls-internal
