apiVersion: v1
kind: Secret
metadata:
    name: internal-dns-secret
    namespace: network
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: ENC[AES256_GCM,data:Hwzm,iv:NjmNEizZVpOlCHvJbCW6S304gmprKzPTBwQrufCAXGw=,tag:4M2p8aDiQjXmCZ4D9Ur0uw==,type:str]
    EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG: ENC[AES256_GCM,data:0UF7vTgEJdpkD9Q=,iv:y2BipLljag+CYjDYIHop0TFDmMrjYu1H7/t6cKX4M18=,tag:Zusf/PjtBdUBKEODa4K69A==,type:str]
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:mK9LxyijJQXGQwlihPuYpq+0PAhTR/0k9flN9HzdF/M0appaZpxxv9boGtXyT7HJC9s5WoHmU0WVqQ03vqhDgc6MGJrYrpprH3tB429DcyOyirIWPuNv5A==,iv:MXlyyXCyBT0YkuI1bIxgUv5sp5t2JuR6QHhPN6W47ww=,tag:83vLwpZYQXYvEvHr4jA9ig==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-01-22T23:36:20Z"
          enc: CiQAFbK3LAmfr0kVxAeRgnUP6lMXxn7/sP9Ru7Pj31II5mBNAAYSSQAN+xHZZg8Dda8KUom+5rWzlg7FpJ+AfgvJRJPnOUgOTO0WzkD+eRGKZC3Scv8eFKDTuTg9cIJB8tPcyesGmbskLiHkEdCQFAw=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQUF0QUVzYURsQzZ3cXZ1
            cVgxaGh6WjhuQlMwTVplSU1ZNjUyK2cvendVCmRwYlA5bkJjZ2dodi90RHBOcm1y
            M2hiL3oxdkdFeXFxL3UzNG9GM29wNEUKLS0tIE1NSENOcUNkZzNBM0oyUFJ0WE9P
            Y0paSHpvY2lUN2dZK3pyNHNMYWNNMVEKBzetagLueYjh1NYbIPyVLxGib3tUlEyH
            lP3uGeMJqPwfnxpZjBmknXBiFcHAtJaIXteVSJwLOmWpFES0q+/lWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-31T23:35:24Z"
    mac: ENC[AES256_GCM,data:3b0gZtLtctOjlnoQ6frva5tIQ7M0xYTTYWpK+BWog/82hxSINrRs0flUp2znmwa/+guZmt96RmBa3KcHljIXGDwk7so8wonNwwra2bt8OsCKnS64VsdTmSahN43k29rlH3NttXcuQHh7ke+pTTy1pQbQ+flUHY8TYL4MU/ANDik=,iv:t7Rp3z45yNsRQ67rzzV/KyY2e9EYVWi2Qc87USnBLgo=,tag:B5unleveWsj6RIUIWG/ogQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
