apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: security
stringData:
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:VuoXQmmvH97IIxUezZFcASRvCXXKFw==,iv:+0LeqsHLmNhtNh/01eGvwUhl42x3ZrKsTJbkMLLLeVg=,tag:vkfTLFnuwO1tOay4w+ei1g==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:g11CYaObeeFYFHOTVPCDu5wzUF6v8j1WjHHXjEz8SJvE1invjE695w==,iv:dX27xt7m306oBeBwVKy0qikvicgkABcCRaFxZGaipTo=,tag:lVM4ymcytIWc43eSNIMWig==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:2eFhXdLrWdKYZYFWHNwm1c3VVpG9k/sDLkELhVpuhLgxVpg+GjaOGbrRCA==,iv:mIE2v/6A1yxS+jibgWama0p7B5YVGykYARncP7E+EvI=,tag:uwAXcoTmYq9KxIpujZ4AFQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:QMhzxXIvWrpAOXPM0DNRqDRkSDV/P9q0EtrJsbquFfIKYu64l04XQGQn,iv:nMP0hBM7LxNNIM8O4QrMjOEe3rb4GiLphjQnfqFSGjY=,tag:Q5m4ZpSUxDISDnDaZvY7Aw==,type:str]
    AUTHENTIK_PLEX_CLIENT_ID: ENC[AES256_GCM,data:jBG0SuVtUjqA4jrBkknZYJygBqiZ74HM,iv:xP+/UkTgzg7sLc+DdrfXrxKOSEQXmhormtLaYSxZd+g=,tag:oX/VUNyjtmcUfTMMeoqTOA==,type:str]
    AUTHENTIK_PLEX_TOKEN: ENC[AES256_GCM,data:bteEtuhDfTw8iuqEqf/rpYUTlrc=,iv:V3YlpOLLyir523yjn3lN8gV0xfpbhX4HP8lwxBBcVdU=,tag:V0Y/VDquEPAiVwdtxbJk0g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-01-25T22:09:14Z"
          enc: CiQAFbK3LCiB8u2ymAdRG9C4p+yKQbVFPoT4zlccCYlAWryO5AgSSQAN+xHZmmh8h9eh6PmWZKkpwp5UUF8UkuSYd7iSpRTRWslvcSeKVlq2hzRC3goRAfmXRYAms3+Q7XHFizpTxXlLGoHZyRrz/4Y=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS3IzQVVFMHhtV0VMbzdG
            dUJpUnU3UjlrZVczaXhDSFV1ekFrK211MWo4CmhwUUJ2cXZ3ZUpZUDdTM0JMME1l
            dFBkOGxRMkJOanJSNlRnRUVtYTBLeGMKLS0tIGh4MUtvZnUwSUl6aHRvSXVtazBL
            Y1JlWC9URVVjZ1RKZjZzU0pzckFEQXMKuDUdZF30PPnFWmN6W7JT+1x/9lH6jT7M
            YcGehwLIV9s83+uU+Ow37yk+sgupbbQXTenUMMMNr9Tr5g5jsouu8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T22:09:15Z"
    mac: ENC[AES256_GCM,data:qQMaayr/xI22M3771Yz1xvGgxPM5huWw1UclrHv/7adg2g/ettYLWp+Hd4AMUghqb2NemXtL2JkzRwzNViCx1b8sAVdQvrEXxHsdeSkrrkGBmp//odNJgKe2XnWXuNXxT5dwSBLKHLqTGzWruKTjk6QP29tVjnVnuqf4XH6YFlU=,iv:Mqtl5c4tVhMQCboH47Y9ycyWGmHX+PzAbzgvdE5xBSU=,tag:zBT3bXXvdv5DHuDEEznnQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
