apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitor
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: true
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: flux-system
stringData:
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:GDhEcwXTMHgicVX4nY60jE0zXHmi0mI17l66nDEVSPedM9FH3wknKDTNE018xM4qFXY=,iv:+Jea+thWLUaOMDTvQPXbW+51AGwEbKbXInX/tIFsVNc=,tag:IW6ATOEGs4WZw3ROqof5Mg==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:kHU/aIvEjL0bIfCzKdZ6/zYcSOlbzseVWFw1FHTh4hzp8S1jH4sfDvjsjzFvcsJkFXFl,iv:jxYJUvdOm8RQ+2vP6icIbWGSCaN2rH/VjsxHJxeRSoY=,tag:FX6iSNy3YSWMmGptbRoeFw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:RnTsJuBo9Q==,iv:y+1hks3QAtboYjqbmGcYi5R6E4rTxldPuNxKPd9A99A=,tag:4oQaxYpkI6sVh0/6q3vzYg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7nl4zfKPZWVqGNrBgVpb503+u9zzFsVUpmrEHbuHjvxQVdIH2SexThkY/foPvC7K8EokYPI=,iv:GAAT1hkAFHvTCOfbm7LMvP0CJn4BhONebyNl3WtDLRw=,tag:ltBLk8BpnnQoo2+zEOgP7w==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:3Ok0OaWeEdRc9nVvwjuiv3GCObZGRmI6sSMAcdrFs2QYcBwV613/bH492kZRGSA=,iv:7EApNBWR03ooUkWE2djdLlz5KG4Ns5X6BRsopzrsjoo=,tag:QwPR6NLWG+cpPeDOw5xPSw==,type:str]
    GF_AUTH_SIGNOUT_REDIRECT_URL: ENC[AES256_GCM,data:lae2awuILTktIC1EBVV3az7p0FA6/9BZoGPLwpwTkgy3alwbK0leFnCpBPmCPoEq2OVaSQgZ/WRTRe+Eag==,iv:aAJ1CzvHU5UeR+y+4vOsCQfuJW8VPahpH9795CUMM0w=,tag:iCzvdHCAWOP2fSip1m1Jxg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-01-25T22:17:41Z"
          enc: CiQAFbK3LHOkxRYtJU1Y6fQTVDCTVeZdVzg/OeLee1Yr4k5GM6ASSQAN+xHZxG0k3feszTSqIlHF+g12a3d6UyYdronbYAyABaHVm7XVU4DmTWHnPWA6+8vWTLEkn+SCN0Mw2cLm/PSvTv3C5xCakHc=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ3RVT3NBYlFGeFVnSDR6
            dnUyNVNmMDJRb0hQUkVaWUdOeVVQdjc3WG1JCkFPWWtMdVhpMW5XWkxEMlBURE1G
            aVVJZTZ6NGFvYy9nbEVHQXBBa1BDbHcKLS0tIGxjRTlnOHZrTDdBK2FldjE3NHcv
            WkNicFQrQWR3UEk1YnFyNUJDK2dJUnMKOvQNOgW7QzkZ6HDFO85/pVNTyOowcCeB
            bBX4QWLCfE0b3EomjCai/Yw9lKEbkjaL83sTRA6Hz4/UGGrKmaMFhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T22:17:42Z"
    mac: ENC[AES256_GCM,data:V2GfKrj/lV4VPTyUvX/l4DKSmadOVUOz7/KX8DoHf+T+Pf3dQB7ZrFG9b+tt9TJDOPR6qCPEsUWN8eX9wwYqK3u18sXVuFWRj0ycxFg/aTY5HhrUB706XpyFGb0xVEXPUwrNiOE9QMhFXFthEDlS5EnHDYSrkNFqN5ITrmNXlus=,iv:u8jZ12TLn4bTv2ljeiT10hdbojGE7juCIwGFdfaVs7Q=,tag:G3D5qakzmRjKWO5u0JGH/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
