apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:k7XdbADaOFeUdbK5wPwoEbw066pIv2jZqgA=,iv:43w25QxaS1tzM3mX2C1F/+PrLOEul0UaObRvN/of02c=,tag:JVFo7wpxiI2N8ruxV9iPEA==,type:str]
    PLEX_SERVER_ID: ENC[AES256_GCM,data:FhfgY1EB0VrN05t5bbk0nFYXwdAtUHqKefembTlAn4wBQ0Yh0FmWwvE=,iv:/dgrqBj1AhhncfbKeRf+I41h208oZOJwn03R9xIIsAc=,tag:q0Rx9271Dp7OLdsbb867RA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-01-25T18:47:35Z"
          enc: CiQAFbK3LDeU/pZUrbDZ1b4s0Wicc3uADSJp5oFKoANUfy6bBVoSSQAN+xHZ+e7AbFulTwiyFWo2zsHsJ4F11mSjMnlxlTH3/L+PkmtpiRtTWYLLAT196Bg0XEOfx8cZ6RuWUDErMvEUiBcaJtOIHjQ=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMmNKMEYvSG4xSG1Fandx
            NU5BUUJSeDZtTmpsYllSU1ZBclI1amcyQkVvCjBNQnl2SlVOd3RJSDdJOXNsS01h
            dE5za2tRSVFLTnAyRHBjZFRmV0xZd0EKLS0tIGE4Vk5icUdSNE5CNDd1M284MzV3
            Y3FKR1dQUnJBUWUzdmN5TldlMU5YSUUKGKuWUWcMUtAJHYjmzN5nZgHCKpWbcEdL
            6sDiQ3Er1pxKo7FeUS1A1tUbEpC7xKl2n18oY7lUhYaEZKsf3KIcUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T19:08:16Z"
    mac: ENC[AES256_GCM,data:Rd3lCL2NsMaiB80Mx9QNVOoxi6s0SIo0E8r+qlXOauvujE/MCnUQGZsvIqvR2ynE/9+lll2I0yrfc01JPBkf0WDfSC1lH8LiVsNDWtmrTNeVvVfFrFb1pxBKu/x0O3/qQ5tAalZZY6If6/qlGAvdsh1L2QAcZLo16mzcpykBdZk=,iv:CyUdr7lWMN6iuc9eIsrT4Ffa0MUOOGxhCYS2xqgb/V0=,tag:Dgsps8q/JJ3VDKITbQ53ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
