apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:r4WJzKxWy+C0kC+w0FYnS/nWPLLvr3AuQsk=,iv:H18EuaMPcR2RoFlfeYhEKGKwJfK7ZGfX+cSBdHwIP6M=,tag:449RejC6NJOMJEU4w8rf7A==,type:str]
    PLEX_SERVER_ID: ENC[AES256_GCM,data:FhfgY1EB0VrN05t5bbk0nFYXwdAtUHqKefembTlAn4wBQ0Yh0FmWwvE=,iv:/dgrqBj1AhhncfbKeRf+I41h208oZOJwn03R9xIIsAc=,tag:q0Rx9271Dp7OLdsbb867RA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-01-25T18:47:35Z"
          enc: CiQAFbK3LDeU/pZUrbDZ1b4s0Wicc3uADSJp5oFKoANUfy6bBVoSSQAN+xHZ+e7AbFulTwiyFWo2zsHsJ4F11mSjMnlxlTH3/L+PkmtpiRtTWYLLAT196Bg0XEOfx8cZ6RuWUDErMvEUiBcaJtOIHjQ=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMmNKMEYvSG4xSG1Fandx
            NU5BUUJSeDZtTmpsYllSU1ZBclI1amcyQkVvCjBNQnl2SlVOd3RJSDdJOXNsS01h
            dE5za2tRSVFLTnAyRHBjZFRmV0xZd0EKLS0tIGE4Vk5icUdSNE5CNDd1M284MzV3
            Y3FKR1dQUnJBUWUzdmN5TldlMU5YSUUKGKuWUWcMUtAJHYjmzN5nZgHCKpWbcEdL
            6sDiQ3Er1pxKo7FeUS1A1tUbEpC7xKl2n18oY7lUhYaEZKsf3KIcUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T19:14:54Z"
    mac: ENC[AES256_GCM,data:DziadJhFSiwLQhzdZ07yMtrFW3jsJrWB8FAMduUtmFSaKmIratYduWy+HnX9o5OIZYoAAD5oiQPo6ZcvYSd1VVaEPBrrF/Ag8kFeg3gY9fDS0oQKPlr0lsrCNo5T+etRzhn1NSuffvF7sVUuqkAXV/7pJzw4ww97hclt8kEnqUc=,iv:ZntlxWmFqfc75R4Jri8Ug1MZswuMdciuBZw2Vgt6G8U=,tag:gAtuUmdhB3NtHLY9RhTQaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
