apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: datastore
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security,home
stringData:
    AWS_SECRET_ACCESS_KEY_ID: ENC[AES256_GCM,data:Mqxux0DBKXWlTw+r9d38yf8J5a0=,iv:gsh7YkuQMegWJL/Pw7HTrFHMxeFdojytdNS8dCwX15k=,tag:n6JUPZdCLRRy8Kzc8CWD3Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:96T4t88Naw3W30ZHxmY3xus2SMpA9hjC/1JhtQ37HD0AhxgkD7wZtw==,iv:bwFfXfCFF8O38sQYeZyBgS/AQOmOqK3ObwbDfSYGV9I=,tag:KKA1hNeYKAvj8gvrNxfSGQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-01-16T22:46:35Z"
          enc: CiQAFbK3LGE07Fmn04MMoLFQJxpUOMuq+WLX3rzqKKKPjnucsgwSSQAN+xHZpM5OUXJNGR5kDTmBPWiumbE4DFj2CP7Nxp4dNI5q4oihkOP3uyWQQGpbK8xmTUgGAOis1G2vZ5mV0/ec6Vhmnp/nWVU=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbkJFcDNicUxEd3dhaTRU
            aUVyVkxNcm9Bb2l4YjNCYWdZdS9wOHlKQlVFCmJVLzVLc3lHWHJBMDJvRFdTcGIv
            a2dhM0grclVERkZDK2p0TWNDbkFDc00KLS0tIHRKR2d5aUVpS2dZaWdzd0N6TnN4
            YzlBSklYTElHdlpkTnN6YWw0eWtscWcKPmjISueWa9gKeDzxTko3xaogn1WNOPGA
            Y9AMQCUGVE66a1QN0CNfkOTeqwucqvxuo8Dk8bgsf7hKzN1Guyq2rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T22:46:35Z"
    mac: ENC[AES256_GCM,data:XxuiZsFs9G3JpOJKBHKZaNI061nKtcDlCgdzmOHeJr30xOQufS/O1+xNfqFpna+u9u4/Gf6LARia0dC3IQ4x77Vix+G0ONznrN7nawp/ZnnIyHq96HrLq5pV1+sVNAet58Lh0FkVuxYzAlY58msZw7pHXWhvoqTJrSH2BIigyi8=,iv:QjbVMQGWNNIxFkJPpj46g2KljX6nTuMvRXnmdd09nxY=,tag:hae15t1JIvMPStFHpk0BJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
