apiVersion: v1
kind: Secret
metadata:
    name: starr-apps-secret
    namespace: media
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: download
stringData:
    RADARR_API_KEY: B63s5rmDMFgIXCbGnrO4Q98LGbFZ1VOHlX5mb2ZVa
    SONARR_API_KEY: yDaOpFmjQl1QdQD4VnC0K39hpYKU904UsBbt82V1aWo
    LIDARR_API_KEY: kYjryw0DUz7kIm5rLPl7p7gjRjoChTg9TZuAL6uMBiz
    READARR_API_KEY: FzrjQm0o5Yw51H4Exz7sI6MPurWlthYi4b7ycFdOu4Y
    BAZARR_API_KEY: keM3GVQuQ7H2UXEMCTebKqdNADgn1N4YGwu90jPKBUE
    PROWLARR_API_KEY: mqVetCGVAL8GczOBSVoPdtAEjEMOy0aeix5muhawdj8
