apiVersion: v1
kind: Secret
metadata:
    name: starr-apps-secret
    namespace: media
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: download
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:eIHuBinq+2SGVHdkPn/ztt48MZ5NOJHEAdwFjSX6B3UGx9oQ65EIT1U9s1jsb0WE,iv:ztNjkBGe2yntREfYitAfP5A1UQIWc8QCsgguenY27Bg=,tag:QV6N/vIhS5rk01YBKQRkUw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:V8t/+9+aNXVx6s8CRp5azOqVVCSRGao0MOJgbYDpVv49IsZ6XMqVk6Vu2znaSerU,iv:ZST4fNq8dq58gi+7db/xUauGMlmnyImGrZG1lvFWmUk=,tag:c9+Uov50k8xCWA4fH0XZ6w==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:Ju8RqUBHRmH8JLFZvEQFEJ1Gom9adNTLIpMH8MuisQmj6SeUSwflzqohvXETCYD1,iv:wfnryc+fzqCW9JRaJzB82w+36bJO0fr50Xac2KSj29Y=,tag:ULtHYs7Lqjig13UV0KJ7Pg==,type:str]
    READARR_API_KEY: ENC[AES256_GCM,data:INprBV8CG4Y2mOk/uQls8lX7OVRXWmi/bNaR1XguskQinzc7Og8/z0nINlLyEflk,iv:ZisZoREl9XMuT5YcHTDsNVPb6jYLBxU9BuinW5fest8=,tag:aOOfSuhgDIFK+O6/oGNYeg==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:VebGSlLG6XwpqbShMGQi3JzIezH52P5nDOk1VWtQSH0GPm3ihzZa3GUnqgGiak24,iv:jkGXNtZI/9/oVFit6Eu5zZOHXDTYCBK3PnP91PJLiQY=,tag:hH/0UQj7tE5oBbsL1P9dag==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:ads0xzdVtEdgLfnzywHFYqmJZJz+evn3xU6ZxW9rIu/EjBRiNzmLEvSwLMDDGSPX,iv:qH3vY8LnfB3bqqizBgaUsjM+/9Sl+QQdVG4cwzR6flA=,tag:fiqYIi5ruAXppIHJVz9/nw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-05-31T21:25:18Z"
          enc: CiQAFbK3LMXbSvAUN98rHzV+NDM6ndUjF1EVS77taGXUvtXneawSSQAN+xHZgMeY+ObXzEEfsVMbbdIXeHaOC86o37LVqogJmcfzMDOcmEzAlbHjsrBgMdDsT9Efh222j0YI+jL5V+dXDeRXEVhZcPA=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycDRnbkNIWHdwcnJVclcv
            VnI5WGpNZWJGOTRmN1RJc2R2akhHQXI3a0IwCkI2Yk1xMEdFemdDRXh5cnVtR2Y4
            U3o3R0x0anlhdmxHMWZHUEE5WWxLdFUKLS0tIHQ5TEtnNEhCVG9MU3hKd0N6ZG5O
            Q2NtV3UxN0d1dWRXTlJGVFFKaVFPcnMKvAf0qCjuZ/kTIzLLuJ4JXqIUMpMDDqgT
            DdQlr4oLS5VtvO4U7neYex44T+aiAEORwmgkhOXHNj3faMAYwrhcMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-31T21:25:19Z"
    mac: ENC[AES256_GCM,data:DTcAgWaD4DDSOHeVwlyTJlYfohwmtCgiSK6FvC6FzSQkLRGW+nVF8zQggWnRkh+8zH9PmoJvtJ5H8qrseLWWwe70bJmQsXH2rI6mqbA5NLo6qHaE6gjqFyQgkLLygcUdiZUSvIUuQpvks6bBHN6aTa5FpCSjO44A0y3si97cB/s=,iv:PFkQvMJI1Lewr6XWfrcpEsICUQ9O4Xe4gFIm6wkRbaE=,tag:SWL5ZNMt8a7PrgjcLGciIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
