apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: network
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:LMrW7U+XnemDB/wEmMLH0rGnbI63/viuN/QYeZlmgmX6dfy4nVjBOw==,iv:eB0lGuGWysWHRd7GIAXCA99mU4TuhRf9u0BoNfuysU0=,tag:sLa2BkR8VXF5oTDsMgWbiQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/homelab-411417/locations/global/keyRings/pollreisz-keyring/cryptoKeys/sops
          created_at: "2024-01-22T23:28:24Z"
          enc: CiQAFbK3LDg3kbJPbzjq8MT0sP0bAVYePTW1SGagGxYxkReVNoASSQAN+xHZRo1Kj7gQIAXUme3WZgT9kcI8ABtrV5PCIFiVPw2EWIDu/yNvA/lvujF9NxIv99PyoMSBs62I/c6F57VoA6Hn869xXx0=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujgpmesszpu8z62w5yfg56srzfjd5v9h2n447yslv5njvqdpjuys9zgsv0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OXVFNGg0aCtWYi9NRGNV
            RGg4dWVWdWhldGdYODA0c0x5VFFtWWRBSlVrCnA4Q2xDL0pxZW9SUWtuV0RZTUpa
            dVNmOHcrb1FmRzBZVWpRZ1JueUtOM0UKLS0tIFRXZkx3NndtaFZxVEVFNit3MHdT
            WE4ya2U0S0U5b2tBNVVqQWJzTWUyMDQKbuHywzT2QRW+LuCY10hqk3Gk9+vfKYai
            2J1t+pxDXe+LIScPMElDY8c5WXoBYPbFnTHlPalCeGYrZeRmzdmuZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T23:28:25Z"
    mac: ENC[AES256_GCM,data:DevKXpmi42eqSw4ezc6bXqeRaRwSBmq47ZdUird8dfBeTKY/z/jk2H//u3VIX9qtQbdgE4EVguZxyOasEEe6vOyMcHKGJxccKvkII4LllbbURwe6Cg0XAKXrNkIDwfg9zKi/5V5z5+jHNnogKVtKQRLsH2tjGVYj1QmY6POlgIQ=,iv:iu98G0mOaLU/JlgYTqY11TmIzqVRSFnKRTJXZJnNZBg=,tag:4K0zojodAjL88HrFiNMUUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
